name: Python Jobs Scraping Scheduled Script

on:
  schedule:
  - cron: "0 6-18/4 * * 1-5"
  - cron: "0 */6 * * 0,6"

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Rome"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Execute Python Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python jobs.py
      - name: Commit Files
        run: |
          git config --local user.name liggiorgio
          git config --local user.email "liggiorgio@live.com"
          git add --all
          git diff-index --quiet HEAD || git commit -am "GH ACTION Jobs Scraping $(date)"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
